### ISSUE TITLE
enum error on first example test when importing polardiagram

### ISSUE THREAD

**Issue by jbfdomage** [hrosailing/hrosailing#112]
**Describe the bug**
when starting the first example given there is an error just when importing the "polardiagram"
  File "/usr/lib/python3.9/enum.py", line 277, in __new__
    if canonical_member._value_ == enum_member._value_:
ValueError: operands could not be broadcast together with shapes (20,) (72,) 

**To Reproduce / Minimal Example**
"import hrosailing.polardiagram as pol"

**Expected behavior**
should go throuh

**Additional context**
enthusiast tester

**Comment by rubbinduck** [comment]
Hi, that is a weird error you have stumbled upon. There should not be any operands to broadcast, when just importing.

Unfortunately I couldn't replicate the error. Would you mind giving me additional infos (such as your python version, the hrosailing version, etc.) so i can hopefully fix it?

Thank you!

**Comment by jbfdomage** [comment]
Windows 10 
Python 3.9.0
Attached a copy of the configuration , code and traceback 
[2023.10.16 JBD Configuration HRO failing.txt](https://github.com/hrosailing/hrosailing/files/12918769/2023.10.16.JBD.Configuration.HRO.failing.txt)

**Comment by jbfdomage** [comment]
C:\Users\j.domage>pip install hrosailing
Requirement already satisfied: hrosailing in c:\python\python39\lib\site-packages (0.11.0)

**Comment by RobertSchueler** [comment]
To provide more technical context here: It seems to be an issue with the numpy version. The recommended numpy  version for hrosailing is 1.22.0. The behaviour you describe happens when using numpy version 1.25.0 or newer (as you did).

In my opinion, the most probable issue can be found in the release notes (https://numpy.org/doc/stable/release/1.25.0-notes.html) as follows: Deprecation: Only ndim-0 arrays are treated as scalars.

**Comment by RobertSchueler** [comment]
Correction: it rather seems to be related to change of `==` operator which, since numpy 1.25.0, throws an error if compared arrays have incompatible shapes instead of returning `false`

**Comment by rubbinduck** [comment]
Yes, that was my explanation as well. It seems the issue comes from that and the creation of the `_Resolution` enum in `_polardiagramtable.py`, as they check the members for duplicate values and perform an `==` check. Since our values are `(np.arange(2, 42, 2), 40)` and `(np.arange(0, 360, 5), 360)` that is the root of the problem.
