### ISSUE TITLE
Unexpected `PolarDiagramException` thrown by `cruise()` from `hrosailing.cruising` when using it on `PolarDiagramMultiSails` or `PolarDiagramTable`

### ISSUE THREAD

**Issue by Loitador41** [hrosailing/hrosailing#79]
**Describe the bug**
When giving `cruise()` the parameter `uv_grd` and trying to use it with an instance of `PolarDiagramMultiSails` or `PolarDiagramTable`, it throws a `PolarDiagramException` which states that a wind speed is given that is not contained in the wind speeds of the polar diagram.

**To Reproduce / Minimal Example**
```python
from hrosailing.cruising import cruise
from hrosailing.polardiagram import from_csv

pd = from_csv("../../examples/csv-format-examples/table_hro_format_example.csv")

print(cruise(pd=pd, ws=16, uv_grd=(2.71667, -1.2889), start=(54.167767, 11.844653), end=(54.225654, 11.904676)))
```

**Additional context**
The exact exception thrown by the example above is the following:
`hrosailing.polardiagram._basepolardiagram.PolarDiagramException: {3.0069185387868425} is not contained in [ 6.  8. 10. 12. 14. 16. 20.]`

**Comment by RobertSchueler** [comment]
This behaviour is as intended. The wind speed of `uv_grd` is 3.0069185387868425 and the table does not have a slice for this particular wind speed.

The following code works since the wind speed is supported by the polar diagram (there are small API changes due to an earlier commit).

```
from hrosailing.cruising import cruise
from hrosailing.polardiagram import from_csv

pd = from_csv("examples/csv-format-examples/table_hro_format_example.csv")

print(cruise(pd=pd, wind=(6, 0), wind_fmt="uv_grd", start=(54.167767, 11.844653), end=(54.225654, 11.904676)))
```

Of course, it would be nice to support cruising for other wind speeds via interpolation.
